### ISSUE TITLE
Feedstock Version not Matching Release Version

### ISSUE THREAD

**Issue by Sparks29032** [conda-forge/pyobjcryst-feedstock#36]
Feedstock is 2024.1, but anaconda release version is 2.2.6. This is an issue when trying to install with libobjcryst version 2024.1.

Might require fixing pypy builds. Ubuntu gives segfault when running tests.

**Comment by vincefn** [comment]
Ok, I hope the mistakes are all corrected by #39 and version 2024.1.1 for both `libobjcryst` and `pyobjcryst`.

Build pipeline [seems OK](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=872552&view=results) , there are just the pypy builds for which I'm unsure of what is going on, I looked at that a few months ago without success.
